# run me with docker-compose -f docker-compose-db.yml up -d


version: '3.4'

services:
  db:
    image: postgres
    container_name: hackapp-db
    volumes:
        - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=hackapp,hackapp_test
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    restart: unless-stopped
