"""Init db

Revision ID: 17490d94556e
Revises: 
Create Date: 2020-05-22 17:32:01.579860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17490d94556e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_models',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=True),
    sa.Column('title', sa.String(length=4096), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_link_models_created'), 'link_models', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_models_created'), table_name='link_models')
    op.drop_table('link_models')
    # ### end Alembic commands ###
